alias tg-56k='/Users/dan/workspace/56k/tg.sh'
alias tg-cr='/Users/dan/workspace/56k/cr/tg.sh'
alias tg-mb='/Users/dan/workspace/56k/mb/tg.sh'
alias tg-ms='/Users/dan/workspace/56k/ms/tg.sh'
alias tg-ms-us='/Users/dan/workspace/56k/ms/tg-us.sh'
alias tf-pg='/Users/dan/workspace/56k/pg/tf.sh'
